### ISSUE TITLE
Script installation 

### ISSUE THREAD

**Issue by webkida** [NETWAYS/notify_usbtlight#2]
Hey a quick question.
I have icinga installed on one of my cloud and access if from my office. I want to setup the light notification in my office. So if I install the script on the cloud where the icinga is installed how will the notification work from any other machine and that too in different location?

How can I achieve that.

**Comment by mxhash** [comment]
Hi,

yes, the plugin pulls the status out of the classic ui (the cgi's). If you have that running you can use the plugin from anywhere where it's reachable.

Cheers,
Marius
